### ISSUE TITLE
Recognize markdown tasks specified with asterisk instead of dash

### ISSUE THREAD

**Issue by MattiasMartens** [roovo/obsidian-card-board#126]
Currently the plugin only detects a task if it is set with a dash like this:

```md
- [ ] my task
```

i would like it to also detect the task if it is set with an asterisk like this:
```md
* [ ] my task
```

both formats are supported by Obsidian.

**Comment by MattiasMartens** [comment]
i see this incapacity is actually enforced with a test case?

```elm
, test "fails to parse a task with a '*' as the list marker" <|
            \() ->
                "* [X] foo"
                    |> Parser.run TaskItemHelpers.basicParser
                    |> Result.mapError (always "failed")
                    |> Expect.equal (Err "failed")
```

any particular reason for that?

**Comment by MattiasMartens** [comment]
if the reason this was excluded is "because it makes it too difficult to correctly toggle in all the cases": my read is it is a fine UX tradeoff to replace "* [ ]" with "- [ ]" in some cases in exchange for "* [ ]" items still appearing on the board. it can cause a lot of confusion why those items aren't showing up when they are indistinguishable in the Obsidian interface.

**Comment by MattiasMartens** [comment]
PR here: https://github.com/roovo/obsidian-card-board/pull/127

**Comment by roovo** [comment]
Hah - well I never!!  I had assumed that only "- [ ]" was valid for tasks, and just used the asterisk as an example in my tests.... But as you point out obsidian also recognises the asterisk.  And thank you for the PR too :)

I'll get this into the next release, which I will be working on where I can this week!  Thank you again

**Comment by roovo** [comment]
This is in the latest release [0.7.0](https://github.com/roovo/obsidian-card-board/releases/tag/0.7.0).  Thank you for the issue and the pull request.  I did add to it, so that it also recognises `+` as a list marker (as this is also valid apparently), and so that the list marker is retained when marking a task as completed on the board.

Thank you again and hopefully all is working as expected for you.  Do let me know if you find any issues with it!
