### ISSUE TITLE
Bug: secondary instances of the CardBoard tab/pane render without task text

### ISSUE THREAD

**Issue by Angush** [roovo/obsidian-card-board#137]
If you split the CardBoard tab into two (such as by right-clicking the tab and selecting "Split right" or "Split down"), the second instance will render with no data, like so:

![image](https://user-images.githubusercontent.com/5266227/215774121-10289726-e3d3-4687-ae6e-5a87d7d19ce0.png)

Noticed this while fiddling with the CSS for #116 (hence the column view). But it also occurs on the latest, unmodified release (0.7.1).

**Comment by roovo** [comment]
Ah ha - that will be because I have built it assuming that there will only be one board instance - darn the ability to have 2 CardBoard views at once ;)

This occurs as I pass the markdown content of each task line back to obsidian to render and use an id on the div on the card to tell it where it needs to go.  This id will be the same for both the boards so it'll be writing the content twice to the first occurrence of the id's in the DOM - meaning one of the boards will be blank.

I could add an additional "cardboard instance" identifier (which in practice would just need to be a shortish random string) to the element id's in the DOM to get around this.

Should be a pretty simple fix so will look into doing this soon as I think it counts as a bug :)

Nice spot!!

**Comment by roovo** [comment]
Got the work for this done - I'll get a new version out over the weekend with this fix in it :)

Thanks again - really appreciated

**Comment by roovo** [comment]
Heya - new version with the fix in it just released (0.7.2) - any probs, just let me know - thanks
