### ISSUE TITLE
card-board Frontmatter tag differs from obsidian frontmatter tags

### ISSUE THREAD

**Issue by AeliusSaionji** [roovo/obsidian-card-board#147]
Following frontmatter tags as per documentation https://help.obsidian.md/Editing+and+formatting/Tags

card-board does not detect the tags.

![image](https://user-images.githubusercontent.com/4342746/227742072-e602a97d-0134-4af8-9aae-0115fffcb873.png)

Where does the inclusion and requirement of `[ ]` brackets originate from?

Thanks

**Comment by AeliusSaionji** [comment]
Picture showing card-board mystery bracket requirement
![image](https://user-images.githubusercontent.com/4342746/227742252-d9b3985a-fe5b-48d8-b364-ece7a92421ef.png)

**Comment by Xananax** [comment]
Second mystery requirement is that this is the only tag of the page

**Comment by roovo** [comment]
[note to self] frontmatter tags decoded in MarkdownFile.frontMatterDecoder

**Comment by roovo** [comment]
As far as I can tell, this is a documentation issue for CardBoard rather than an actual issue with the plugin itself. lf I have a file containing

```
---
tags:
  - colab
  - foo
---

# Colaboration examples

- [ ] need to ask #people/fred if he can loan me is dinosaur @due(2024-01-04)

- [ ] decorate my cave @due(2024-01-11)
  - [x] ask #people/wilma to do a cave painting @due(2024-01-04)
  - [ ] borrow design book from #people/barney
  - [ ] check everyone can make the painting party @due(2024-01-08)
```
These tasks appear in a tag based column which is specified to use the tag `#foo`:
![Screenshot 2024-01-05 at 08 53 31](https://github.com/roovo/obsidian-card-board/assets/5251/b02f9ed9-cd29-40c5-81ec-d08f37039ff2)

The documentation in the next release will be updated to use the same format as in the Obsidian docs.  I am expecting to release this pretty soon and will close this issue when I do.

Please do let me know if I have misunderstood the issue tho!

**Comment by AeliusSaionji** [comment]
heh, obsidian changed how they handle tags since I made this issue.

See here: 
https://github.com/obsidianmd/obsidian-help/commit/68624afe9a1029d68d752816a7509a5504fadc37#diff-7f234324fbaa76cd5bc3bf4147a2792fbf54ab0103285b981c9375bb5b417622L34

`tags: tag1, tag2`
This still works but is no longer documented.

**Comment by roovo** [comment]
thanks for confirming that - much appreciated!

I'll have a look at this in the morning and add support for the `tags: tag1, tag2` format if it's straightfoward to do as I would like to be able to work with the same formats that obsidian itself can (documented or not).  Otherwise it will have to wait for the next release as I want to get the next release out tomorrow

Thanks again

**Comment by roovo** [comment]
...and added and released.  I've left it as an undocumented feature - in line with Obsidian :)

Thank you again for raising this
