### ISSUE TITLE
您好，请问能否识别tasks插件的循环任务符号，我在看板中点击完成一个具有循环任务符号的任务无法创建新任务

### ISSUE THREAD

**Issue by lxmwwl** [roovo/obsidian-card-board#194]

**Comment by roovo** [comment]
You should raise any issues with the tasks plugin here: https://github.com/obsidian-tasks-group/obsidian-tasks

If you are saying that when you mark a recurring task as complete inside CardBoard the new task is not created, then this is because CardBoard does not handle recurring tasks.  Track progress on this at #164.
