### ISSUE TITLE
Add option to ignore files/folders for processing

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#27]
I use templates pretty extensively. Some of those templates include tasks that I would like to include on the board but I don't want them actually on the board until the template is used. It would be nice to be able to set some files or folders to be ignored when processing files to look for tasks so that the tasks in the templates won't be included on the board.

**Comment by roovo** [comment]
I have been thinking the same thing myself, for the same reason as well as that I have a folder full of quite a lot of old "Evernote -> Joplin -> Obsidian" notes that I'm sure if I ignored would speed up loading time.

Do you think that this should be a global configuration, rather than per board.  If there are no real solid use cases for making it per board this is what I would favor...

**Comment by darthmachina** [comment]
My use case would be global. I could maybe see a use case for the reverse idea, to have an option to limit processing to a set of files/folders. I could see people keeping their project management stuff in a folder and setting that folder to be the only thing that CardBoard looks at would speed up processing as well.

**Comment by roovo** [comment]
I am planning on adding an option to select either/both folders/tags to use when building a board in the board settings for exactly this [#22] :)

So in combination with the global option your suggesting this should be pretty powerful!

**Comment by rhhub** [comment]
+1 to this. As someone new to trying this, I ran into the need for this pretty quick. On a date board, the undated section has a lot of entries from my templates folder.

**Comment by roovo** [comment]
just released version 0.7.6 which includes this :)
