### ISSUE TITLE
Put CardBoard on sidebar with custom icon

### ISSUE THREAD

**Issue by darthmachina** [roovo/obsidian-card-board#30]
This is one I'm not sure about but wanted to at least submit for discussion.

I'm wondering if it would be a good idea to have CardBoard be added to the sidebar on load instead of being one of the icons in the ribbon? Similar to how the Calendar plugin works when enabled. For me, I've dragged the page that's loaded onto the right sideboard and it seems to work really well. But it does just get the normal page icon instead of a dedicated one.

Huh, I thought it would limit you to just having it in a sidebar but I can drag the Calendar view onto the main board just fine. So, this would just be the default spot for it. And it would have a custom icon then as well which I think would be really nice.

**Comment by roovo** [comment]
Don't you find that the side-bar is a bit narrow?  The view is kinda built with a landscape rather than portrait feel to it, which is why I went straight for the main content windows.  For it to work in the side bar, it would probably need to have keyboard navigation to save scrolling and perhaps better/custom styling for such narrow windows.

So I'm not sure on the merits of this, but happy to see how it gets used in the wild and work from there.

On the Icon: I presume there must be a way to attach an icon to the view so that when it is dragged into the sidebar it shows up.  Just had a quick look and I see that there is an icon property in the View class in obsidian API so that might do it.  I'll add a note onto the 'Happenings' project for adding the icon as that is a no-brainer!

**Comment by darthmachina** [comment]
TBH, the icon thing would probably work just as well, as pages can be dragged into the sidebar as-is. 

And the sidebar can be adjusted to be any width, just like pages. Right now I have about a 50-50 split between the notes area and the sidebar. The nice thing about having it in the sidebar for me is that when I click to edit a task CardBoard stays the same width as the note is opened in the note area and divides the space between notes, leaving the sidebar the same width. But, like I said, having it as a regular page it can still be dragged to the sidebar. 

I'd be good with just setting the icon so it stands out a little more as not being a regular note, and it makes it more visible in the sidebar when it's tabbed with other items that exist there.

**Comment by roovo** [comment]
Interesting, I've only ever left the sidebar as a narrow thing that I quite often hide!  Just had a little play and it is kinda nice that you can show and hide the kanban easily, and it stays as it is without  being impacted by any notes you have open.  Will have to experiment more with how I'm using obsidian!

**Comment by roovo** [comment]
not suing the parked list any more, so re-opening.

**Comment by roovo** [comment]
Closing this one as the icon is in place and there is a more specific issue about supporting a single column view which I think is integral to better sidebar use/support.  I don't plan on changing things so that CardBoard opens in the sidebar by default.
